# Generated by Django 6.0.3 on 2026-09-30 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_normalize_phone_numbers'),
        ('users', '0005_remove_customuser_full_name_customuser_patronymic'),
    ]

    operations = [
    ]
