# Generated by Django 6.0.3

import django.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carbrand_alter_car_options_alter_car_brand_carmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='car',
            name='is_archived',
            field=models.BooleanField(
                default=False,
                verbose_name='Архивный',
            ),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.UniqueConstraint(
                condition=django.db.models.Q(vin__isnull=False),
                fields=('owner', 'vin'),
                name='unique_car_owner_vin',
            ),
        ),
    ]
