# Generated by Django 6.0.3

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count, Q


def create_initial_ownership_history(apps, schema_editor):
    Car = apps.get_model('cars', 'Car')
    CarOwnership = apps.get_model('cars', 'CarOwnership')

    CarOwnership.objects.bulk_create(
        CarOwnership(
            car_id=car.pk,
            owner_id=car.owner_id,
        )
        for car in Car.objects.all().only('id', 'owner_id').iterator()
    )


def validate_unique_vins(apps, schema_editor):
    Car = apps.get_model('cars', 'Car')

    duplicates = (
        Car.objects
        .filter(vin__isnull=False)
        .exclude(vin='')
        .values('vin')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )

    if duplicates.exists():
        raise RuntimeError(
            'Невозможно включить глобальную уникальность VIN: '
            'в таблице cars_car есть дублирующиеся VIN. '
            'Сначала необходимо объединить/исправить эти записи.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_archiving'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(validate_unique_vins, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='car',
            name='unique_car_owner_vin',
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.UniqueConstraint(
                condition=Q(vin__isnull=False) & ~Q(vin=''),
                fields=('vin',),
                name='unique_car_vin',
            ),
        ),
        migrations.CreateModel(
            name='CarOwnership',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=__import__('uuid').uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'started_at',
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    'ended_at',
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    'car',
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name='ownership_history',
                        to='cars.car',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name='car_ownerships',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'История владения автомобилем',
                'verbose_name_plural': 'История владения автомобилями',
                'ordering': ('-started_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='carownership',
            constraint=models.UniqueConstraint(
                condition=Q(ended_at__isnull=True),
                fields=('car',),
                name='unique_current_car_ownership',
            ),
        ),
        migrations.RunPython(create_initial_ownership_history, migrations.RunPython.noop),
    ]
