# Generated by Django 6.0.3

from django.db import migrations, models


def backfill_vehicle_snapshots(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')

    for order in Order.objects.select_related('car__brand', 'car__model').iterator():
        car = order.car
        order.car_brand_snapshot = car.brand.name
        order.car_model_snapshot = car.model.name
        order.car_year_snapshot = car.year
        order.car_vin_snapshot = car.vin
        order.car_plate_number_snapshot = car.plate_number
        order.save(
            update_fields=(
                'car_brand_snapshot',
                'car_model_snapshot',
                'car_year_snapshot',
                'car_vin_snapshot',
                'car_plate_number_snapshot',
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_busy_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car_brand_snapshot',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='car_model_snapshot',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='car_year_snapshot',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='car_vin_snapshot',
            field=models.CharField(max_length=64, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='car_plate_number_snapshot',
            field=models.CharField(max_length=20, blank=True, null=True),
        ),
        migrations.RunPython(backfill_vehicle_snapshots, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='car_brand_snapshot',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='car_model_snapshot',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='car_year_snapshot',
            field=models.PositiveIntegerField(),
        ),
    ]
